/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'STM32-CMSIS-Libs.Release+STM32F103VC' 
 * Target:  'Release+STM32F103VC' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* Keil::CMSIS Driver:SPI@2.2 */
#define RTE_Drivers_SPI1                /* Driver SPI1 */
#define RTE_Drivers_SPI2                /* Driver SPI2 */
#define RTE_Drivers_SPI3                /* Driver SPI3 */
/* Keil::CMSIS Driver:USART@2.3 */
#define RTE_Drivers_USART1              /* Driver USART1 */
#define RTE_Drivers_USART2              /* Driver USART2 */
#define RTE_Drivers_USART3              /* Driver USART3 */
#define RTE_Drivers_USART4              /* Driver UART4  */
#define RTE_Drivers_USART5              /* Driver UART5  */


#endif /* RTE_COMPONENTS_H */
